<!--
  Breadcrumb — where this page sits, and the way back out.

  It is an ordered list inside a labelled `<nav>` because that is what assistive
  tech expects to find, and the last crumb is text with `aria-current="page"`
  rather than a link to where you already are. The separators are generated by
  CSS and marked `aria-hidden`, so nobody hears "slash" four times.

  On a narrow screen a deep trail wraps into a paragraph of grey text, which
  helps no one. Past `collapseAfter` the middle collapses to an ellipsis and the
  first and last crumbs survive — origin and position are the two the reader
  actually uses.
-->
<script lang="ts">
  import type { HTMLAttributes } from 'svelte/elements';
  import { cn } from '../../utils/cn.js';
  import type { Crumb } from '../../types.js';

  interface Props extends Omit<HTMLAttributes<HTMLElement>, 'children'> {
    items: Crumb[];
    /** Collapse the middle once the trail is longer than this. */
    collapseAfter?: number;
    label?: string;
  }

  let {
    items,
    collapseAfter = 4,
    label = 'Breadcrumb',
    class: className,
    ...rest
  }: Props = $props();

  let expanded = $state(false);

  const collapsed = $derived(items.length > collapseAfter && !expanded);

  /** First, a gap, then the last two: enough to say "you are here, under that". */
  const shown = $derived(collapsed ? [items[0], ...items.slice(-2)] : items);
  const gapAfter = $derived(collapsed ? 0 : -1);
  const hidden = $derived(items.length - shown.length);
</script>

<nav data-an="breadcrumb" class={cn('an-crumbs', className)} aria-label={label} {...rest}>
  <ol class="an-crumbs__list">
    {#each shown as crumb, i (crumb.label + i)}
      {@const last = i === shown.length - 1}
      <li class="an-crumbs__item">
        {#if last}
          <span class="an-crumbs__current" aria-current="page">{crumb.label}</span>
        {:else if crumb.href}
          <a class="an-crumbs__link" href={crumb.href}>{crumb.label}</a>
        {:else}
          <span class="an-crumbs__link">{crumb.label}</span>
        {/if}
      </li>

      {#if i === gapAfter}
        <li class="an-crumbs__item">
          <button
            class="an-crumbs__more"
            type="button"
            aria-label={`Show ${hidden} hidden ${hidden === 1 ? 'level' : 'levels'}`}
            onclick={() => (expanded = true)}
          >
            …
          </button>
        </li>
      {/if}
    {/each}
  </ol>
</nav>

<style>
  .an-crumbs {
    font-family: var(--an-font-sans);
    font-size: var(--an-text-footnote-size);
    min-width: 0;
  }

  .an-crumbs__list {
    display: flex;
    align-items: center;
    flex-wrap: wrap;
    gap: 2px;
    margin: 0;
    padding: 0;
    list-style: none;
  }

  .an-crumbs__item {
    display: flex;
    align-items: center;
    min-width: 0;
  }

  /* Generated separator, invisible to assistive tech — the list structure
     already conveys the hierarchy, and "slash" read aloud four times does not. */
  .an-crumbs__item + .an-crumbs__item::before {
    content: '/';
    margin-inline: 6px;
    color: var(--an-text-faint);
  }

  .an-crumbs__link,
  .an-crumbs__current {
    display: block;
    max-width: 22ch;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }

  .an-crumbs__link {
    color: var(--an-text-muted);
    text-decoration: none;
    border-radius: var(--an-radius-xs);
  }

  @media (hover: hover) {
    a.an-crumbs__link:hover {
      color: var(--an-text);
      text-decoration: underline;
      text-underline-offset: 2px;
    }
  }

  .an-crumbs__current {
    color: var(--an-text);
    font-weight: var(--an-weight-medium);
  }

  .an-crumbs__more {
    display: grid;
    place-items: center;
    min-width: 24px;
    height: 24px;
    padding: 0 4px;
    border: none;
    border-radius: var(--an-radius-sm);
    background: none;
    color: var(--an-text-faint);
    font: inherit;
    line-height: 1;
    cursor: pointer;
  }

  @media (hover: hover) {
    .an-crumbs__more:hover {
      background: var(--an-surface-hover);
      color: var(--an-text);
    }
  }
</style>
